### PR TITLE
Add unique identifier for documented environment variables and remove…

### LINKED ISSUE #26: Support duplicate 'envvar' parameters
Our use case is to have an option which is common to multiple commands.
This option has an `envvar` parameter.
This gives a warning.
I think that this is a valid, not warning-worthy error.
Perhaps `sphinx-click` should differentiate the built environment variable blocks somehow.

A small reproducible case follows:

`hello.py`:

```python
import click

@click.command()
@click.option('--foo', envvar='EXAMPLE')
def A(foo):
    pass

@click.command()
@click.option('--foo', envvar='EXAMPLE')
def B(foo):
    pass
```

`source/index.rst`:

```rst
.. click:: hello:A
   :prog: hello

.. click:: hello:B
   :prog: hello
```

Building the docs shows the following error:

```
hello:1: WARNING: Duplicate explicit target name: "cmdoption-hello--foo".
/Users/dev/Workspace/sphinx-envvar/source/index.rst:3: WARNING: Duplicate ID: "envvar-EXAMPLE".
```

Found with @mhrabovcin.

### PR DESCRIPTION
**Pull request by adamtheturtle**
… them from the index.

Fixes #26 .

### CODE REVIEW

**Comment by stephenfin** [comment]
You need to fix the style checks here. I'm not sure about removing these from the index though. Shouldn't it be possible to count the environment variables we have found and simply include a reference to an existing one if they're duplicated?

**Comment by adamtheturtle** [comment]
The style issues appear unrelated.

**Comment by mimischi** [comment]
Any news on this PR? Just realized we are also experiencing this issue.

**Comment by stephenfin** [comment]
> The style issues appear unrelated.

@adamtheturtle Indeed. Have rebased and just waiting on CI results before merging. Thanks!

**Pull request merged**
