### PR TITLE
Improved code style to pass Tox

### PR DESCRIPTION
**Pull request by jirikuncar**
includes #19 
addresses #21 - see also https://travis-ci.org/jirikuncar/sphinx-click/builds/301993087

### CODE REVIEW

**Comment by stephenfin** [comment]
@jirikuncar Not sure if this is necessary anymore (I resolved said issues before I spotted this 😞 ), and It seems to have squashed in some of the changes from #19. What do you want to do?

**Comment by jirikuncar** [comment]
@stephenfin I have resolved the conflicts.

**Comment by jirikuncar** [comment]
@stephenfin will you agree on changing `pep8` target to `style` which would include `isort` and `yapf` (and possible `pydocstyle`)?

**Comment by stephenfin** [comment]
> > @stephenfin will you agree on changing pep8 target to style which would include isort and yapf (and possible pydocstyle)?
> 
> Go for it 👍

If you do this though, you need to make sure the target doesn't actually make any changes to the code. If it does, the `pep8` target becomes useless as the gate will now format the code, pass the tests, and then not save the code because it doesn't commit it.

**Comment by jirikuncar** [comment]
@stephenfin I have addressed your latest comments. The `yapf` tool only checks that there are no differences, but it doesn't change the code itself.

**Comment by stephenfin** [comment]
Thanks for the quick follow-ups, @jirikuncar

**Pull request merged**
