### PR TITLE
display `show_default` string even when `default=None`

### LINKED ISSUE #93: Display `show_default` string even when `default=None`
# Current behavior

The option

```python
@click.option('--foo', show_default='mydefault')
```

will not have a default documented

# Expected behavior

The text `mydefault` is documented as the default value for this option.

# What now?

Looking at the code [here](https://github.com/click-contrib/sphinx-click/blob/6aeee375067483337b5cfda98233d4fb1a1addb1/sphinx_click/ext.py#L76), the fix seems relatively straightforward.

I'd like to submit a PR if you agree :)

### PR DESCRIPTION
**Pull request by ariebovenberg**
fixes #93

### CODE REVIEW

**Comment by stephenfin** [comment]
Could you fix the failing lint job (run `tox -e pep8` locally) and I'll merge this

**Comment by ariebovenberg** [comment]
@stephenfin done.

**Comment by stephenfin** [comment]
Thank you!

**Comment by ariebovenberg** [comment]
@stephenfin no problem :).  looking forward to using this

**Pull request merged**
