### PR TITLE
Mock mod

### PR DESCRIPTION
**Pull request by prajeeshag**
## Tasks

- [ ] Added unit tests
- [ ] Added documentation for new features (where applicable)
- [ ] Added release notes (using [`reno`](https://pypi.org/project/reno/))
- [ ] Ran test suite and style checks and built documentation (`tox`)

### CODE REVIEW

**Comment by peytondmurray** [comment]
Hey, I'd really like to see mocking capability merged into `sphinx-click`. Is there anything I can do to move this PR along? 

Also, does it make sense to use `autodoc_mock_modules` here? In my use case I'd sure like to just be able to define mocks in one place, rather than having to specify a separate list of `click_mock_imports`.

I'd be happy to make a PR against this branch if needed - just let me know how I can help.

**Comment by prajeeshag** [comment]
Hi @peytondmurray, Thanks for your interest in merging mocking capability.

Yes, `autodoc_mock_modules` can be used directly, and I don't see any need for a separate list. I don't remember why I created that.

Please feel free to create a PR, and pardon me if I am saying something stupid here because I have no prior experience in contributing to an open-source project.  I don't know the process. Your help in this regard is really appreciated, thanks.

**Comment by stephenfin** [comment]
Looks like this has stagnated so I'm going to close. Please reopen if you'd like to continue working on this

**Comment by stephenfin** [comment]
Also, @peytondmurray did this in #129. Whoops :smile:

**Pull request closed without merging**
